# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  mail:
    host: smtp.qq.com
    username: test@qq.com
    password: abcd
    ssl:
      enabled: true
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/qwq
    username: qwqqwqqwq
    password: qwqqwqqwq
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 100
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  minio:
    endpoint: 'http://localhost:9000'
    username: 'minioadmin'
    password: 'minioadmin'
  weather:
    api-host: 'qwq'
    key: qwq
  ai:
    deepseek:
      api-key: 'qwq'
